# Task file for GitHub Actions, https://taskfile.dev/

version: "3"

# https://taskfile.dev/usage/#env-files
dotenv: [".env.local", ".env"]

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task --list-all
    silent: true

  build-prod:
    desc: "Build application for production"
    cmds:
      - task setup-network
      - task composer-install
      - task npm-install
      - task install-cleanup

  setup-network:
    desc: "Setup docker frontend network"
    cmds:
      - docker network create frontend

  composer-install:
    desc: "Install dependencies with composer."
    cmds:
      - docker compose run --rm --env APP_ENV=prod phpfpm composer install --no-dev -o --classmap-authoritative
      - docker compose run --rm --env APP_ENV=prod phpfpm composer clear-cache

  npm-install:
    desc: "Installs node dependencies with npm."
    cmds:
      - docker compose run --rm node npm install
      - docker compose run --rm node npm run build

  install-cleanup:
    desc: "Cleanup after install"
    cmds:
      - rm -rf infrastructure
      - rm -rf fixtures
      - rm -rf tests
      - rm -rf node_modules
