monolog:
    channels:
        [
            'outbound_http',
            'auth',
            'screen',
            'media',
            'feed',
            'interactive',
            'cache',
        ]
