<?php

namespace App\Tests;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use App\Entity\ScreenGroup;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

class ScreenGroupsTest extends ApiTestCase
{
    use RefreshDatabaseTrait;

    public function testGetCollection(): void
    {
        $response = static::createClient()->request('GET', '/v1/screenGroups?itemsPerPage=2');

        $this->assertResponseIsSuccessful();
        // Asserts that the returned content type is JSON-LD (the default)
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        // Asserts that the returned JSON is a superset of this one
        $this->assertJsonContains([
            '@context' => '/contexts/ScreenGroup',
            '@id' => '/v1/screenGroups',
            '@type' => 'hydra:Collection',
            'hydra:totalItems' => 10,
            'hydra:view' => [
                '@id' => '/v1/screenGroups?itemsPerPage=2&page=1',
                '@type' => 'hydra:PartialCollectionView',
                'hydra:first' => '/v1/screenGroups?itemsPerPage=2&page=1',
                'hydra:last' => '/v1/screenGroups?itemsPerPage=2&page=5',
                'hydra:next' => '/v1/screenGroups?itemsPerPage=2&page=2',
            ],
        ]);

        $this->assertCount(2, $response->toArray()['hydra:member']);
        $this->assertMatchesResourceCollectionJsonSchema(ScreenGroup::class, 'get-v1-screen-groups');
    }

//    public function testCreateBook(): void
//    {
//        $response = static::createClient()->request('POST', '/books', ['json' => [
//            'isbn' => '0099740915',
//            'title' => 'The Handmaid\'s Tale',
//            'description' => 'Brilliantly conceived and executed, this powerful evocation of twenty-first century America gives full rein to Margaret Atwood\'s devastating irony, wit and astute perception.',
//            'author' => 'Margaret Atwood',
//            'publicationDate' => '1985-07-31T00:00:00+00:00',
//        ]]);
//
//        $this->assertResponseStatusCodeSame(201);
//        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
//        $this->assertJsonContains([
//            '@context' => '/contexts/Book',
//            '@type' => 'Book',
//            'isbn' => '0099740915',
//            'title' => 'The Handmaid\'s Tale',
//            'description' => 'Brilliantly conceived and executed, this powerful evocation of twenty-first century America gives full rein to Margaret Atwood\'s devastating irony, wit and astute perception.',
//            'author' => 'Margaret Atwood',
//            'publicationDate' => '1985-07-31T00:00:00+00:00',
//            'reviews' => [],
//        ]);
//        $this->assertMatchesRegularExpression('~^/books/\d+$~', $response->toArray()['@id']);
//        $this->assertMatchesResourceItemJsonSchema(Book::class);
//    }
//
//    public function testCreateInvalidBook(): void
//    {
//        static::createClient()->request('POST', '/books', ['json' => [
//            'isbn' => 'invalid',
//        ]]);
//
//        $this->assertResponseStatusCodeSame(422);
//        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
//
//        $this->assertJsonContains([
//            '@context' => '/contexts/ConstraintViolationList',
//            '@type' => 'ConstraintViolationList',
//            'hydra:title' => 'An error occurred',
//            'hydra:description' => 'isbn: This value is neither a valid ISBN-10 nor a valid ISBN-13.
//title: This value should not be blank.
//description: This value should not be blank.
//author: This value should not be blank.
//publicationDate: This value should not be null.',
//        ]);
//    }
//
//    public function testUpdateBook(): void
//    {
//        $client = static::createClient();
//        // findIriBy allows to retrieve the IRI of an item by searching for some of its properties.
//        // ISBN 9786644879585 has been generated by Alice when loading test fixtures.
//        // Because Alice use a seeded pseudo-random number generator, we're sure that this ISBN will always be generated.
//        $iri = $this->findIriBy(Book::class, ['isbn' => '9781344037075']);
//
//        $client->request('PUT', $iri, ['json' => [
//            'title' => 'updated title',
//        ]]);
//
//        $this->assertResponseIsSuccessful();
//        $this->assertJsonContains([
//            '@id' => $iri,
//            'isbn' => '9781344037075',
//            'title' => 'updated title',
//        ]);
//    }
//
//    public function testDeleteBook(): void
//    {
//        $client = static::createClient();
//        $iri = $this->findIriBy(Book::class, ['isbn' => '9781344037075']);
//
//        $client->request('DELETE', $iri);
//
//        $this->assertResponseStatusCodeSame(204);
//        $this->assertNull(
//        // Through the container, you can access all your services from the tests, including the ORM, the mailer, remote API clients...
//            static::$container->get('doctrine')->getRepository(Book::class)->findOneBy(['isbn' => '9781344037075'])
//        );
//    }
}
