import { api as generatedApi } from "./generated-api";

export const enhancedApi = generatedApi.enhanceEndpoints({
  endpoints: Object.fromEntries(
    Object.entries(generatedApi.endpoints).map(([key, endpoint]) => {
      const enhancedEndpoint = {
        ...endpoint,
        invalidatesTags: ["region"],
      };

      return [key, enhancedEndpoint];
    })
  )}
);

export const {
  useGetOidcAuthTokenItemQuery,
  useGetOidcAuthUrlsItemQuery,
  usePostLoginInfoScreenMutation,
  usePostRefreshTokenItemMutation,
  useGetV2FeedSourcesQuery,
  usePostV2FeedSourcesMutation,
  useGetV2FeedSourcesByIdQuery,
  usePutV2FeedSourcesByIdMutation,
  useDeleteV2FeedSourcesByIdMutation,
  useGetV2FeedSourcesByIdConfigAndNameQuery,
  useGetV2FeedSourcesByIdSlidesQuery,
  useGetV2FeedsQuery,
  useGetV2FeedsByIdQuery,
  useGetV2FeedsByIdDataQuery,
  useGetV2LayoutsQuery,
  useGetV2LayoutsByIdQuery,
  useLoginCheckPostMutation,
  useGetV2MediaQuery,
  usePostMediaCollectionMutation,
  useGetv2MediaByIdQuery,
  useDeleteV2MediaByIdMutation,
  useGetV2CampaignsByIdScreenGroupsQuery,
  useGetV2CampaignsByIdScreensQuery,
  useGetV2PlaylistsQuery,
  usePostV2PlaylistsMutation,
  useGetV2PlaylistsByIdQuery,
  usePutV2PlaylistsByIdMutation,
  useDeleteV2PlaylistsByIdMutation,
  useGetV2PlaylistsByIdSlidesQuery,
  usePutV2PlaylistsByIdSlidesMutation,
  useDeleteV2PlaylistsByIdSlidesAndSlideIdMutation,
  useGetV2SlidesByIdPlaylistsQuery,
  usePutV2SlidesByIdPlaylistsMutation,
  useGetScreenGroupCampaignItemQuery,
  useGetV2ScreenGroupsQuery,
  usePostV2ScreenGroupsMutation,
  useGetV2ScreenGroupsByIdQuery,
  usePutV2ScreenGroupsByIdMutation,
  useDeleteV2ScreenGroupsByIdMutation,
  useGetV2ScreenGroupsByIdCampaignsQuery,
  usePutV2ScreenGroupsByIdCampaignsMutation,
  useDeleteV2ScreenGroupsByIdCampaignsAndCampaignIdMutation,
  useGetV2ScreenGroupsByIdScreensQuery,
  useGetV2ScreensQuery,
  usePostV2ScreensMutation,
  useGetV2ScreensByIdQuery,
  usePutV2ScreensByIdMutation,
  useDeleteV2ScreensByIdMutation,
  usePostScreenBindKeyMutation,
  useGetV2ScreensByIdCampaignsQuery,
  usePutV2ScreensByIdCampaignsMutation,
  useDeleteV2ScreensByIdCampaignsAndCampaignIdMutation,
  useGetV2ScreensByIdRegionsAndRegionIdPlaylistsQuery,
  usePutPlaylistScreenRegionItemMutation,
  useDeletePlaylistScreenRegionItemMutation,
  useGetV2ScreensByIdScreenGroupsQuery,
  usePutV2ScreensByIdScreenGroupsMutation,
  useDeleteV2ScreensByIdScreenGroupsAndScreenGroupIdMutation,
  usePostScreenUnbindMutation,
  useGetV2SlidesQuery,
  usePostV2SlidesMutation,
  useGetV2SlidesByIdQuery,
  usePutV2SlidesByIdMutation,
  useDeleteV2SlidesByIdMutation,
  useApiSlidePerformActionMutation,
  useGetV2TemplatesQuery,
  useGetV2TemplatesByIdQuery,
  useGetV2TenantsQuery,
  useGetV2TenantsByIdQuery,
  useGetV2ThemesQuery,
  usePostV2ThemesMutation,
  useGetV2ThemesByIdQuery,
  usePutV2ThemesByIdMutation,
  useDeleteV2ThemesByIdMutation,
  useGetV2UsersQuery,
  usePostV2UsersMutation,
  useGetV2UsersByIdQuery,
  usePutV2UsersByIdMutation,
  useDeleteV2UsersByIdMutation,
  useDeleteV2UsersByIdRemoveFromTenantMutation,
  useGetV2UserActivationCodesQuery,
  usePostV2UserActivationCodesMutation,
  usePostV2UserActivationCodesActivateMutation,
  usePostV2UserActivationCodesRefreshMutation,
  useGetV2UserActivationCodesByIdQuery,
  useDeleteV2UserActivationCodesByIdMutation,
} = enhancedApi;
