---
resources:
    App\Entity\ScreenLayoutRegions:
        output: App\Dto\ScreenLayoutRegions
        normalization_context:
            groups: ['read']

        operations:
            ApiPlatform\Metadata\Get:
                security: 'is_granted("VIEW", {type: "SCREEN_LAYOUT_REGIONS", object: object})'
                uriTemplate: '/layouts/regions/{id}'
                controller: App\Controller\Api\NotFoundAction
                openapiContext:
                    # For backward compatibility
                    operationId: getScreenLayoutRegionsItem

            ApiPlatform\Metadata\GetCollection:
                security: 'is_granted("LIST", {type: "SCREEN_LAYOUT_REGION"})'
                uriTemplate: '/layouts/regions'
                controller: App\Controller\Api\NotFoundAction
                openapiContext:
                    # For backward compatibility
                    operationId: getScreenLayoutRegionsCollection
