on: pull_request

name: Api Spec

env:
  COMPOSE_USER: runner

jobs:
  apispec:
    runs-on: ubuntu-latest
    name: API Specification validation
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup network
        run: docker network create frontend

      - name: Install Dependencies
        run: docker compose run --rm phpfpm composer install

      - name: Export specifications (yaml)
        run: docker compose run --rm phpfpm bin/console api:openapi:export --yaml --output=public/api-spec-v2.yaml --no-interaction

      - name: Check for changes in specifications (yaml)
        run: git diff --diff-filter=ACMRT --exit-code public/api-spec-v2.yaml

      - name: Export specifications (json)
        run: docker compose run --rm phpfpm bin/console api:openapi:export --output=public/api-spec-v2.json --no-interaction

      - name: Check for changes in specifications (json)
        run: git diff --diff-filter=ACMRT --exit-code public/api-spec-v2.json
