on: pull_request

name: Code Analysis

env:
  COMPOSE_USER: runner

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup network
        run: docker network create frontend

      - name: Install Dependencies
        run: docker compose run --rm phpfpm composer install

      - name: PHPStan
        run: docker compose run --rm phpfpm vendor/bin/phpstan analyse --no-progress
