on: pull_request

name: Composer install

env:
  COMPOSE_USER: runner

jobs:
  test-composer-install:
    runs-on: ubuntu-latest
    name: Composer install in prod mode
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup network
        run: docker network create frontend

      - name: "[prod] Composer install"
        run: docker compose run --rm --no-deps -e APP_ENV=prod phpfpm composer install --no-dev -o
