on:
  push:
    tags:
      - "*.*.*"

name: Create Github Release

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        run: |
          docker network create frontend
          docker compose run --rm --user=root --env APP_ENV=prod phpfpm composer install --no-dev -o --classmap-authoritative
          docker compose run --rm --user=root --env APP_ENV=prod phpfpm composer clear-cache
          rm -rf infrastructure

      - name: Make assets dir
        run: |
          mkdir -p ../assets

      - name: Create archive
        run: |
          tar \
            -zcf ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz ./*

      - name: Create checksum
        run: sha256sum ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz > ../assets/checksum.txt

      - name: Create a release in GitHub and uploads assets
        run: |
          gh release create ${{ github.ref_name }} --verify-tag --generate-notes ../assets/*.*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
