on: pull_request

name: Test

env:
  COMPOSE_USER: runner

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: PHP Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache vendor
        uses: actions/cache@v5
        with:
          path: vendor
          key: vendor-php8.4-${{ hashFiles('composer.lock') }}
          restore-keys: vendor-php8.4-

      - name: Setup network
        run: docker network create frontend

      - name: Install Dependencies
        run: docker compose run --rm phpfpm composer install

      - name: PHP Unit - Test setup
        run: docker compose run --rm phpfpm composer run test-setup

      - name: PHP Unit - Run tests
        run: docker compose run --rm phpfpm composer run test
