on: pull_request

name: Rector

env:
  COMPOSE_USER: runner

jobs:
  rector:
    runs-on: ubuntu-latest
    name: Rector
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup network
        run: docker network create frontend

      - name: Install Dependencies
        run: docker compose run --rm phpfpm composer install

      - name: Rector
        run: docker compose run --rm phpfpm vendor/bin/rector --dry-run
