on: pull_request

name: Rector

env:
  COMPOSE_USER: runner

jobs:
  rector:
    runs-on: ubuntu-latest
    name: Rector
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache vendor
        uses: actions/cache@v5
        with:
          path: vendor
          key: vendor-php8.4-${{ hashFiles('composer.lock') }}
          restore-keys: vendor-php8.4-

      - name: Setup network
        run: docker network create frontend

      - name: Install Dependencies
        run: docker compose run --rm --no-deps phpfpm composer install

      - name: Rector
        run: docker compose run --rm --no-deps phpfpm vendor/bin/rector --dry-run
